import { CurrencyPipe } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';

import { AdminService } from '../../core/admin/admin.service';
import { AdminUser, Branch, Category, City, Color, ProductDetail, ProductSummary, Size, Supplier } from '../../core/models/admin.models';

type Section = 'overview' | 'users' | 'locations' | 'masters' | 'suppliers' | 'products';

@Component({
  standalone: true,
  imports: [CurrencyPipe, ReactiveFormsModule],
  template: `
    <div class="admin-layout">
      <aside class="admin-sidebar"><p class="eyebrow">Workspace</p><h1>Control<br><em>center.</em></h1><nav class="admin-nav"><button [class.current]="section === 'overview'" (click)="section = 'overview'">Resumen</button><button [class.current]="section === 'users'" (click)="section = 'users'">Usuarios</button><button [class.current]="section === 'locations'" (click)="section = 'locations'">Ciudades y sucursales</button><button [class.current]="section === 'masters'" (click)="section = 'masters'">Catálogo base</button><button [class.current]="section === 'suppliers'" (click)="section = 'suppliers'">Proveedores</button><button [class.current]="section === 'products'" (click)="section = 'products'">Productos</button></nav></aside>
      <section class="admin-content">
        @if (error) { <p class="error admin-alert">{{ error }}</p> }
        @if (section === 'overview') { <div class="admin-heading"><div><p class="eyebrow">Administración</p><h2>Resumen operativo</h2></div></div><div class="stat-grid"><button (click)="section = 'users'"><strong>{{ users.length }}</strong><span>Usuarios</span></button><button (click)="section = 'products'"><strong>{{ products.length }}</strong><span>Productos</span></button><button (click)="section = 'locations'"><strong>{{ branches.length }}</strong><span>Sucursales</span></button><button (click)="section = 'suppliers'"><strong>{{ suppliers.length }}</strong><span>Proveedores</span></button></div><div class="admin-note"><span>01</span><p>Gestiona la base de tu tienda desde un único espacio. Los cambios se reflejan directamente en el catálogo público.</p></div> }
        @if (section === 'users') { <div class="admin-heading"><div><p class="eyebrow">Administración</p><h2>Usuarios</h2></div><button class="button button-dark" (click)="showUserForm = !showUserForm">{{ showUserForm ? 'Cerrar' : 'Nuevo usuario' }}</button></div>@if (showUserForm) { <form [formGroup]="userForm" (ngSubmit)="createUser()" class="admin-form compact"><input placeholder="Nombres" formControlName="first_name"><input placeholder="Apellidos" formControlName="last_name"><input placeholder="Correo" type="email" formControlName="email"><input placeholder="Teléfono" formControlName="phone"><input placeholder="Contraseña" type="password" formControlName="password"><select formControlName="role"><option value="CLIENT">CLIENT</option><option value="ADMIN">ADMIN</option><option value="BRANCH_MANAGER">BRANCH_MANAGER</option><option value="CASHIER">CASHIER</option><option value="SUPPLIER">SUPPLIER</option></select><button class="button button-dark" [disabled]="userForm.invalid">Crear</button></form> }<div class="table-wrap"><table><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Estado</th><th></th></tr></thead><tbody>@for (user of users; track user.id) { <tr><td><strong>{{ user.first_name }} {{ user.last_name }}</strong></td><td>{{ user.email }}</td><td><span class="tag">{{ user.role }}</span></td><td>{{ user.is_active ? 'Activo' : 'Inactivo' }}</td><td><button class="small-button" (click)="toggleUser(user)">{{ user.is_active ? 'Desactivar' : 'Activar' }}</button></td></tr> }</tbody></table></div> }
        @if (section === 'locations') { <div class="admin-heading"><div><p class="eyebrow">Estructura física</p><h2>Ciudades y sucursales</h2></div></div><div class="split-panels"><div class="admin-panel"><h3>Ciudades</h3><form [formGroup]="cityForm" (ngSubmit)="createCity()" class="inline-form"><input placeholder="Nueva ciudad" formControlName="name"><button class="button button-dark" [disabled]="cityForm.invalid">Añadir</button></form>@for (city of cities; track city.id) { <div class="list-row"><span>{{ city.name }}</span><button class="small-button" (click)="toggleCity(city)">{{ city.is_active ? 'Desactivar' : 'Activar' }}</button></div> }</div><div class="admin-panel"><h3>Sucursales</h3><form [formGroup]="branchForm" (ngSubmit)="createBranch()" class="admin-form"><select formControlName="city_id"><option value="">Ciudad</option>@for (city of cities; track city.id) { <option [value]="city.id">{{ city.name }}</option> }</select><input placeholder="Nombre" formControlName="name"><input placeholder="Dirección" formControlName="address"><input placeholder="Teléfono" formControlName="phone"><button class="button button-dark" [disabled]="branchForm.invalid">Añadir sucursal</button></form>@for (branch of branches; track branch.id) { <div class="list-row"><span><strong>{{ branch.name }}</strong><small>{{ branch.city_name }} · {{ branch.address }}</small></span><button class="small-button" (click)="toggleBranch(branch)">{{ branch.is_active ? 'Desactivar' : 'Activar' }}</button></div> }</div></div> }
        @if (section === 'masters') { <div class="admin-heading"><div><p class="eyebrow">Datos administrables</p><h2>Catálogo base</h2></div></div><div class="master-grid"><div class="admin-panel"><h3>Categorías</h3><form [formGroup]="categoryForm" (ngSubmit)="createCategory()" class="inline-form"><input placeholder="Nueva categoría" formControlName="name"><button class="button button-dark" [disabled]="categoryForm.invalid">Añadir</button></form>@for (category of categories; track category.id) { <div class="list-row"><span>{{ category.name }}</span><button class="small-button" (click)="toggleMaster('categories', category)">{{ category.is_active ? '×' : 'Activar' }}</button></div> }</div><div class="admin-panel"><h3>Tallas</h3><form [formGroup]="sizeForm" (ngSubmit)="createSize()" class="inline-form"><input placeholder="Ej. M" formControlName="name"><button class="button button-dark" [disabled]="sizeForm.invalid">Añadir</button></form>@for (size of sizes; track size.id) { <div class="list-row"><span>{{ size.name }}</span><button class="small-button" (click)="toggleMaster('sizes', size)">{{ size.is_active ? '×' : 'Activar' }}</button></div> }</div><div class="admin-panel"><h3>Colores</h3><form [formGroup]="colorForm" (ngSubmit)="createColor()" class="inline-form"><input placeholder="Nombre" formControlName="name"><input placeholder="#000000" formControlName="hex_code"><button class="button button-dark" [disabled]="colorForm.invalid">Añadir</button></form>@for (color of colors; track color.id) { <div class="list-row"><span><i class="color-dot" [style.background]="color.hex_code || '#aaa'"></i>{{ color.name }}</span><button class="small-button" (click)="toggleMaster('colors', color)">{{ color.is_active ? '×' : 'Activar' }}</button></div> }</div></div> }
        @if (section === 'suppliers') { <div class="admin-heading"><div><p class="eyebrow">Cadena de suministro</p><h2>Proveedores</h2></div><button class="button button-dark" (click)="showSupplierForm = !showSupplierForm">{{ showSupplierForm ? 'Cerrar' : 'Nuevo proveedor' }}</button></div>@if (showSupplierForm) { <form [formGroup]="supplierForm" (ngSubmit)="createSupplier()" class="admin-form compact"><input placeholder="Nombre comercial" formControlName="trade_name"><input placeholder="Razón social" formControlName="legal_name"><input placeholder="Identificación fiscal" formControlName="tax_id"><input placeholder="Correo" type="email" formControlName="email"><input placeholder="Teléfono" formControlName="phone"><input placeholder="Dirección" formControlName="address"><button class="button button-dark" [disabled]="supplierForm.invalid">Crear proveedor</button></form> }<div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Identificación</th><th>Contacto</th><th>Estado</th><th></th></tr></thead><tbody>@for (supplier of suppliers; track supplier.id) { <tr><td>{{ supplier.trade_name }}</td><td>{{ supplier.tax_id || '—' }}</td><td>{{ supplier.email || '—' }}</td><td>{{ supplier.is_active ? 'Activo' : 'Inactivo' }}</td><td><button class="small-button" (click)="toggleSupplier(supplier)">{{ supplier.is_active ? 'Desactivar' : 'Activar' }}</button></td></tr> }</tbody></table></div> }
        @if (section === 'products') { <div class="admin-heading"><div><p class="eyebrow">Inventario comercial</p><h2>Productos</h2></div><button class="button button-dark" (click)="showProductForm = !showProductForm">{{ showProductForm ? 'Cerrar' : 'Nuevo producto' }}</button></div>@if (showProductForm) { <form [formGroup]="productForm" (ngSubmit)="createProduct()" class="admin-form compact"><select formControlName="category_id"><option value="">Categoría</option>@for (category of categories; track category.id) { <option [value]="category.id">{{ category.name }}</option> }</select><input placeholder="Código" formControlName="code"><input placeholder="Nombre" formControlName="name"><input placeholder="Slug" formControlName="slug"><input placeholder="Precio" type="number" formControlName="price"><input placeholder="Descripción" formControlName="description"><button class="button button-dark" [disabled]="productForm.invalid">Crear producto</button></form> }<div class="table-wrap"><table><thead><tr><th>Producto</th><th>Código</th><th>Precio</th><th>Estado</th><th></th></tr></thead><tbody>@for (product of products; track product.id) { <tr [class.selected-row]="selectedProduct?.id === product.id"><td><button class="link-button" (click)="selectProduct(product)">{{ product.name }}</button></td><td>{{ product.code }}</td><td>{{ product.price | currency:'BOB':'symbol':'1.2-2' }}</td><td>{{ product.is_active ? 'Activo' : 'Inactivo' }}</td><td><button class="small-button" (click)="toggleProduct(product)">{{ product.is_active ? 'Desactivar' : 'Activar' }}</button></td></tr> }</tbody></table></div>@if (selectedProduct) { <div class="admin-panel variant-panel"><h3>Variantes de {{ selectedProduct.name }}</h3><form [formGroup]="variantForm" (ngSubmit)="addVariant()" class="inline-form"><select formControlName="size_id"><option value="">Talla</option>@for (size of sizes; track size.id) { <option [value]="size.id">{{ size.name }}</option> }</select><select formControlName="color_id"><option value="">Color</option>@for (color of colors; track color.id) { <option [value]="color.id">{{ color.name }}</option> }</select><input placeholder="SKU" formControlName="sku"><button class="button button-dark" [disabled]="variantForm.invalid">Añadir variante</button></form>@for (variant of selectedProduct.variants; track variant.id) { <span class="variant-chip">{{ variant.size_name }} / {{ variant.color_name }} · {{ variant.sku }}</span> }</div> } }
      </section>
    </div>
  `,
})
export class AdminComponent {
  private readonly api = inject(AdminService);
  private readonly fb = inject(FormBuilder);
  section: Section = 'overview';
  error = '';
  users: AdminUser[] = [];
  cities: City[] = [];
  branches: Branch[] = [];
  categories: Category[] = [];
  sizes: Size[] = [];
  colors: Color[] = [];
  suppliers: Supplier[] = [];
  products: ProductSummary[] = [];
  selectedProduct: ProductDetail | null = null;
  showUserForm = false;
  showSupplierForm = false;
  showProductForm = false;
  readonly userForm = this.fb.nonNullable.group({ first_name: ['', Validators.required], last_name: ['', Validators.required], email: ['', [Validators.required, Validators.email]], phone: ['', Validators.required], password: ['', [Validators.required, Validators.minLength(8)]], role: ['CLIENT', Validators.required] });
  readonly cityForm = this.fb.nonNullable.group({ name: ['', Validators.required] });
  readonly branchForm = this.fb.nonNullable.group({ city_id: ['', Validators.required], name: ['', Validators.required], address: ['', Validators.required], phone: ['', Validators.required] });
  readonly categoryForm = this.fb.nonNullable.group({ name: ['', Validators.required] });
  readonly sizeForm = this.fb.nonNullable.group({ name: ['', Validators.required] });
  readonly colorForm = this.fb.nonNullable.group({ name: ['', Validators.required], hex_code: [''] });
  readonly supplierForm = this.fb.nonNullable.group({ trade_name: ['', Validators.required], legal_name: [''], tax_id: [''], email: ['', Validators.email], phone: [''], address: [''] });
  readonly productForm = this.fb.nonNullable.group({ category_id: ['', Validators.required], code: ['', Validators.required], name: ['', Validators.required], slug: ['', Validators.required], price: [0, [Validators.required, Validators.min(0.01)]], description: [''] });
  readonly variantForm = this.fb.nonNullable.group({ size_id: ['', Validators.required], color_id: ['', Validators.required], sku: ['', Validators.required] });

  constructor() { this.loadAll(); }

  private loadAll(): void {
    this.api.users().subscribe((page) => this.users = page.items);
    this.api.cities().subscribe((page) => this.cities = page.items);
    this.api.branches().subscribe((page) => this.branches = page.items);
    this.api.categories().subscribe((page) => this.categories = page.items);
    this.api.sizes().subscribe((page) => this.sizes = page.items);
    this.api.colors().subscribe((page) => this.colors = page.items);
    this.api.suppliers().subscribe((page) => this.suppliers = page.items);
    this.api.products().subscribe((page) => this.products = page.items);
  }

  private fail(): void { this.error = 'No se pudo completar la operación. Verifica los datos.'; }
  createUser(): void { if (this.userForm.invalid) return; this.api.createUser(this.userForm.getRawValue()).subscribe({ next: (item) => { this.users = [item, ...this.users]; this.userForm.reset({ role: 'CLIENT' }); this.showUserForm = false; }, error: () => this.fail() }); }
  toggleUser(item: AdminUser): void { this.api.setUserActive(item.id, !item.is_active).subscribe({ next: (updated) => item.is_active = updated.is_active, error: () => this.fail() }); }
  createCity(): void { if (this.cityForm.invalid) return; this.api.createCity(this.cityForm.getRawValue().name).subscribe({ next: (item) => { this.cities = [...this.cities, item]; this.cityForm.reset(); }, error: () => this.fail() }); }
  toggleCity(item: City): void { this.api.setCityActive(item.id, !item.is_active).subscribe({ next: (updated) => item.is_active = updated.is_active, error: () => this.fail() }); }
  createBranch(): void { if (this.branchForm.invalid) return; const raw = this.branchForm.getRawValue(); this.api.createBranch({ ...raw, city_id: Number(raw.city_id) }).subscribe({ next: (item) => { this.branches = [...this.branches, item]; this.branchForm.reset(); }, error: () => this.fail() }); }
  toggleBranch(item: Branch): void { this.api.setBranchActive(item.id, !item.is_active).subscribe({ next: (updated) => item.is_active = updated.is_active, error: () => this.fail() }); }
  createCategory(): void { if (this.categoryForm.invalid) return; this.api.createCategory(this.categoryForm.getRawValue()).subscribe({ next: (item) => { this.categories = [...this.categories, item]; this.categoryForm.reset(); }, error: () => this.fail() }); }
  createSize(): void { if (this.sizeForm.invalid) return; this.api.createSize(this.sizeForm.getRawValue().name).subscribe({ next: (item) => { this.sizes = [...this.sizes, item]; this.sizeForm.reset(); }, error: () => this.fail() }); }
  createColor(): void { if (this.colorForm.invalid) return; this.api.createColor(this.colorForm.getRawValue()).subscribe({ next: (item) => { this.colors = [...this.colors, item]; this.colorForm.reset(); }, error: () => this.fail() }); }
  toggleMaster(path: 'categories' | 'sizes' | 'colors', item: Category | Size | Color): void { this.api.setMasterActive(path, item.id, !item.is_active).subscribe({ next: () => item.is_active = !item.is_active, error: () => this.fail() }); }
  createSupplier(): void { if (this.supplierForm.invalid) return; this.api.createSupplier(this.supplierForm.getRawValue()).subscribe({ next: (item) => { this.suppliers = [...this.suppliers, item]; this.supplierForm.reset(); this.showSupplierForm = false; }, error: () => this.fail() }); }
  toggleSupplier(item: Supplier): void { this.api.setSupplierActive(item.id, !item.is_active).subscribe({ next: (updated) => item.is_active = updated.is_active, error: () => this.fail() }); }
  createProduct(): void { if (this.productForm.invalid) return; const raw = this.productForm.getRawValue(); this.api.createProduct({ ...raw, category_id: Number(raw.category_id), variants: [], images: [], supplier_ids: [] }).subscribe({ next: (item) => { this.products = [item, ...this.products]; this.productForm.reset({ price: 0 }); this.showProductForm = false; }, error: () => this.fail() }); }
  toggleProduct(item: ProductSummary): void { this.api.setProductActive(item.id, !item.is_active).subscribe({ next: (updated) => item.is_active = updated.is_active, error: () => this.fail() }); }
  selectProduct(item: ProductSummary): void { this.api.product(item.id).subscribe({ next: (product) => this.selectedProduct = product, error: () => this.fail() }); }
  addVariant(): void { if (!this.selectedProduct || this.variantForm.invalid) return; const raw = this.variantForm.getRawValue(); this.api.addVariant(this.selectedProduct.id, { ...raw, size_id: Number(raw.size_id), color_id: Number(raw.color_id) }).subscribe({ next: (product) => { this.selectedProduct = product; this.variantForm.reset(); }, error: () => this.fail() }); }
}
